version: '3'
services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
